### ISSUE TITLE
Support query params in endpoint

### ISSUE THREAD

**Issue by RCasatta** [Kixunil/payjoin#12]
this line of code

https://github.com/Kixunil/payjoin/blob/70d97ecab05088b53bf26a0d9dba8e03aa6d42ab/bip78/src/sender/mod.rs#L399

triggered me some suspect about the sanity of the endpoint string, is it already free of `?` ?

unfortunately at the moment, this code passes:

```
let uri = Uri::from_str("bitcoin:TB1Q6D3A2W975YNY0ASUVD9A67NER4NKS58FF0Q8G4?amount=1&pj=http://example.com?ciao").unwrap();
assert_eq!(uri.endpoint, "http://example.com?ciao");
```

So we are not yet performing a sanity check on it.

we should probably decide on #3 before fixing this

**Comment by Kixunil** [comment]
FTR BIP78 neither explicitly allows nor forbids `?` in `pj` (presumably url-encoded - one more thing we're missing)
I have a draft e-mail for Nicolas Dorier with a bunch of questions regarding BIP78, I guess I should add this one, finish it and send. :) LMK your e-mail address if you'd like to be in CC.

**Comment by RCasatta** [comment]
yeah riccardo [dot] casatta [🐌] gmail [dot] com

**Comment by Kixunil** [comment]
Sent.
