### ISSUE TITLE
percent-encoding-rfc3986

### ISSUE THREAD

**Issue by Kixunil** [Kixunil/payjoin#24]
Pinging @RCasatta that I forked `percent-encoding` to create [`percent-encoding-rfc3986`](https://github.com/Kixunil/percent-encoding-rfc3986) crate which I intend to be an important component of BIP21 crate I'm working on which will in turn be used here. I'd love for it to receive a review from fresh mind. :)
If it's too much, for you just diffing the crates could work.

Of course anyone else is also more than welcome to do a review.

The crate contains two instances of what I believe to be straightforward use of `unsafe` one of them being copied from the original crate.

Regarding BIP21 status/overview: I'm researching serde-like (but much simpler) deserialization with guarantee that `req-` fields will be processed correctly - either they are known or will cause failure. Types being deserialized will receive `percent_encoding_rfc3986::PercentDecode<'a>` in an argument.

**Comment by RCasatta** [comment]
Some additional context https://github.com/Kixunil/payjoin/issues/3#issuecomment-902782224

**Comment by RCasatta** [comment]
Maybe a naive question, in https://github.com/Kixunil/payjoin/issues/3#issuecomment-902782224 the main reason to fork is the handling of `%`, but isn't it something handled through `AsciiSet` ?

I did some fuzzing: round-trip and decoding random bytes string didn't generate any panic. https://github.com/Kixunil/percent-encoding-rfc3986/compare/master...RCasatta:fuzz?expand=1

There are links to the URL spec https://url.spec.whatwg.org/ in the docs shouldn't they be removed or changed to point to RFC3986?

There is a non-breaking-space in this line https://github.com/Kixunil/percent-encoding-rfc3986/blob/80ee89af4bb6b4e9ba40544cfc54b3ff0d218164/src/lib.rs#L144

**Comment by Kixunil** [comment]
> but isn't it something handled through `AsciiSet` ?

Not really, the issue is that URL spec says that string `%wtf` should be decoded as `%wtf`, while RFC 3986 (indirectly) says it's invalid. In Rust this translates to returning `T` vs `Result<T, DecodeError>`.

> I did some fuzzing: round-trip and decoding random bytes string didn't generate any panic. https://github.com/Kixunil/percent-encoding-rfc3986/compare/master...RCasatta:fuzz?expand=1

Awesome, thanks!

> There are links to the URL spec https://url.spec.whatwg.org/ in the docs shouldn't they be removed or changed to point to RFC3986?

Yes, they should, I tried to remove all references (except for comparison doc) but things may have slipped by.

> There is a non-breaking-space in this line https://github.com/Kixunil/percent-encoding-rfc3986/blob/80ee89af4bb6b4e9ba40544cfc54b3ff0d218164/src/lib.rs#L144

:+1: That one got imported from the original lib. I was thinking of splitting and cleaning up the whole thing but decided to explicitly do it in separate step to make it clearer what changes were made and to not deal with multiple compiler errors at once.

**Comment by Kixunil** [comment]
Closing this will continue discussions related to it there.
