### ISSUE TITLE
Change endpoint from str to URL?

### ISSUE THREAD

**Issue by RCasatta** [Kixunil/payjoin#3]
at the moment something like:
`bitcoin:TB1Q6D3A2W975YNY0ASUVD9A67NER4NKS58FF0Q8G4?amount=1&pj=http://a`
is parsed as a valid bip78 URI, did you consider having field `endpoint` in `Uri` struct to be a parsed URL instead of str (even at the cost of adding a dep)?

**Comment by Kixunil** [comment]
Intriguing, although I'd like BIP21 parser to be eventually in `bitcoin` or as a separate crate and I guess it won't be accepted there. Perhaps as an optional feature.

**Comment by RCasatta** [comment]
Also considering #12 I think we should have URL for bip78, maybe we should have a `Bip21Uri` which recognize only bip21 fields and then Bip78Uri which also recognize pj as URL so that we can have `Bip21Uri` in rust-bitcoin without additional deps and the URL dep only if one wants to use payjoin

**Comment by Kixunil** [comment]
I was thinking more about having all fields in `Bip21Uri` somehow generically.

One strawman way to do it:

```rust
struct Bip21Uri<Extra = SkipUnknown> where Extra: for<'a> FromIterator<(&'a str, Cow<'a str>)> {
    pub address: Address, // maybe it should be `Option<Address>` because some extensions of BIP21 allow leaving it out but BIP21 strictly doesn't and it may be annoying in most cases to manually check it.
    pub amount: Option<amount::Amount>,
    // other known pub fields like description etc
    pub extra: Extra,
}

struct SkipUnknown; // impl FromIterator by dropping everything unknown
```

Apart from `Cow` this approach doesn't needlessly allocate if the fields are going to be dropped anyway. (`Cow` is used because value may or may not be URL encoded)
The right implementation can not use `FromIterator` directly because it needs to be fallible and also must correctly handle `req-` fields but the trait will look very similar.

**Comment by Kixunil** [comment]
I think yes, we should use `url::Url` for endpoint. I think most (all?) consumers will depend on `url` anyway (via `hyper` or so), so dependency is not an issue. Perhaps we should propose `bip21` module for `bitcoin` first though.

**Comment by Kixunil** [comment]
One more interesting thing:

BIP21 specifies that URI is RFC 3986. However `percent_encoding` crate uses [url spec](https://url.spec.whatwg.org/#percent-encoded-bytes) which does specifies that strings like this: `%wtf` should just not percent-decode - resulting to `%wtf`.
RFC 3986 says:

> Because the percent ("%") character serves as the indicator for
>  percent-encoded octets, it must be percent-encoded as "%25"

So my understanding is that it forbids strings like `%wtf`.

I didn't find any suitable library for RFC 3986 or its percent encoding, so we will need to roll our own. (I intend to fork `percent_encoding`.)

**Comment by RCasatta** [comment]
> I didn't find any suitable library for RFC 3986 or its percent encoding, so we will need to roll our own. (I intend to fork percent_encoding.)

did you consider also https://crates.io/crates/uriparse ?

**Comment by Kixunil** [comment]
Hmm, I don't remember seeing that one when I looked. From what I can see:

* The crate looks medium-quality, the documentation is not detailed but neither missing, it contains a bunch of tests including fuzzing, there was no change past last 9 moths yet it isn't 1.0.
* The crate allocates exactly once, I had no-allocation design in mind but not a big deal I guess.
* `Query` is not actually percent-decoded, it does decode internally to check for normalization but the decoded string is not exposed. Therefore my crate is still required.
* There's no method for iterating over `&`-separated components of the query (maybe it's unrelated to RFC 3986, don't remember), so our handling is still needed. This also implies we need to implement `req-` handling ourselves.
* The crate contains a bunch of things we don't need but they don't seem to be too large. 
* No explicit commitment to MSRV

I will check how many things need to be validated when parsing URIs. If it's only a few things (which I suspect to be the case), then I think it'll be easier to just NIH them in BIP21 crate. If there are many or with complicated edge cases I will try to work with developers of `uriparse` to get it to our desired state.

**Comment by anishagg17** [comment]
Hi, if no one is working on this one I would like to work over the fix.

**Comment by Kixunil** [comment]
Sure, I think it shouldn't be hard.
