### ISSUE TITLE
Rename `UncheckedProposal` or `xProposal` to `P2epRequest`

### ISSUE THREAD

**Issue by DanGould** [Kixunil/payjoin#34]
In the spec diagram the messages are called `Original PSBT` and `PayJoin Proposal PSBT`. A receiver  could easily confuse the sender's request, named `Proposal`, for what it is supposed to return. Also, this project is called `PayJoin` when it can also create non-payjoin topology transactions using Pay to endpoint. It might be better named P2ep even if the crate is bip78

cc @evanlinjin

**Comment by Kixunil** [comment]
`UncheckedProposal` is referring to the state, not PSBT. Perhaps call it `ProposalStateUnchecked` instead or something if that's not clear. You pass `PayJoin Proposal PSBT` in an argument and then work with the state. Thankfully the API makes confusion harlmless anyway.
