### ISSUE TITLE
avoid assert in non-test code?

### ISSUE THREAD

**Issue by RCasatta** [Kixunil/payjoin#5]
I think `input_pairs` should return `Result` to avoid the `assert_eq!` https://github.com/Kixunil/payjoin/blob/9c964513571f401860297751937e527a0b0d784f/bip78/src/psbt.rs#L20

**Comment by Kixunil** [comment]
I view it more as programmer error - something inputted transaction with different lengths of `global.unsigned_tx.input` and `inputs`. But I guess it's better to unwrap a `Result` in the caller in certain cases (deserialization guarantees correct lengths) as the caller can distinguish whether PSBT came from trusted source or not.

Side note: In the future I'd like to see a different `Psbt` type with compile-time guarantee of being consistent and working with that instead.

**Comment by RCasatta** [comment]
Even though deserialization guarantees correct lengths it's a valid point I have a rationale that to be fuzzer-friendly the code must always be panic-free.

(the fuzzer potentially could create the struct directly instead of starting from a byte-stream)

**Comment by Kixunil** [comment]
What is fuzzer supposed to find if not panics?

**Comment by RCasatta** [comment]
Yeah you got a point, I meant something like expected-panic-free so the fuzzer could discover other less-expected panics

If you want we can close and re-open if and when a fuzzer can hit the assert (as you said you shouldn't hit by passing through deserialization)

**Comment by Kixunil** [comment]
I believe refactor may be reasonable given that some code could later call that function despite coming from other source. Basically I like to keep panic but move it to the caller.
