### ISSUE TITLE
Test with freshly installed BTCPay wallet (without funds)

### ISSUE THREAD

**Issue by RCasatta** [Kixunil/payjoin#6]
I tested a freshly created BTCPay instance, so without UTXOs the server can't add its input and it simply broadcast the proposal.

In this case the payjoin-client example throws:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValidationError { internal: Decode(Io(Custom { kind: InvalidData, error: InvalidByte(0, 123) })) }', payjoin-client/src/main.rs:62:47`

Even though it should just warn the tx went through without additional input from the receiver

**Comment by Kixunil** [comment]
Yeah, wee need to finish handling of error responses and our own broadcast after one minute.

I guess you already noticed that second transaction goes through. :)

**Comment by Kixunil** [comment]
Opened #7 and #8 to track these cleanly.
